### ISSUE TITLE
DomQuery::fromHtml() E_USER_WARNING for html inside javascript

### ISSUE THREAD

**Issue by tulinkry** [nette/tester#337]
Inline scripts in html which contain some sort of html markup lead the test to fail with `E_USER_WARNING`.

```
-- FAILED: front/presenters/GalleryPresenterTest.phpt
   Exited with error code 255 (expected 0)
   E_USER_WARNING: Tester\DomQuery::fromHtml: Unexpected end tag : div
    on line 7.
```

Html markup inside js string is completely ok so I'm not sure why this should fail.

Code to reproduce this:

``` php
    public function testTester () {
        $html = <<<EOT
<html>
    <head>
    </head>
    <body>
        <script type="text/javascript">
            $(function() {
                $('<div>').html('<div></div>').appendTo($('body'));
            });
        </script>
    </body>
</html>
EOT;
        DomQuery::fromHtml($html);
        Assert::true(true);
    }
```

**Comment by mrtnzlml** [comment]
I had the same issue and I solved it using this [workaround](https://github.com/mrtnzlml/testbench/blob/master/src/Traits/TPresenter.php#L127-L128). But at this point I am sure I don't want to use `Tester\DomQuery::fromHtml` respectively `DOMDocument` because it causes more problems than it should (or I am not able to configure it correctly).

**Comment by milo** [comment]
A little bit related to #336

**Comment by tulinkry** [comment]
Thank you
