### ISSUE TITLE
Cache Runner::findTests / initiateTestCase

### ISSUE THREAD

**Issue by JanTvrdik** [nette/tester#369]
- bug report? no
- feature request? yes
- version: df5e87f

`Tester\Runner\Runner::findTests` has always been very slow when using test cases, mostly because of initiateTestCase. With the recent improvement which makes Tester run failed tests first, this has become even bigger issue than before.

Our application has about ~300 test cases and the findTests phase takes about 20 seconds (~15 second is pure Tester code, about 5 second is our bootstrap).

**Comment by milo** [comment]
It is due to `@testCase` methods discovery run I guess. It is ~70ms per test case, it is not so much but in such amout...

I was thinking about that and I see this ways:
a) discover test methods by parsing PHP code, but it is problematic due to inheritance

b) `require testCase.phpt` instead of run it, but it is problematic from many point of views, duplicit TestCase class names mainly

c) now we have `--temp`, so we can cache test methods list based on mtime() of test file (would need some refactoring, test methods can be inherited)

The c) seems OK to me. Any other ideas?

**Comment by milo** [comment]
I hope solved by  #378
