### ISSUE TITLE
Dumper bug in version 1.7.1

### ISSUE THREAD

**Issue by dakujem** [nette/tester#386]
Version: 1.7.1

I would have provided a PR, but there is no branch to create on. Check out this commit for fix: https://github.com/nette/tester/commit/b1e566b9c53fbdeb53d22de21dd7d0cac5b1a334

**Comment by milo** [comment]
Is there any reason you cannot use v2.0? It has been fixed in it.

**Comment by dakujem** [comment]
I switched to 2.0. But not everyone can as it's a breaking release. This is a 3 minute fix including the release. Why not fix this for those using 1.7 ?

**Comment by milo** [comment]
The only reason for missing 1.7 branch is, that we want to keep only master. Much more comfortable and less time consuming for maintanance. Of course, branch can be created in case of "emergency", but it is not now, sorry. This fix has been fixed by David (51727ac2af61bf47d7a4a8f1f192934eb9ea27a2) one year ago and has been present long time before it. No one complaind.

Tester v2.0 is breaking release, but from user point of view, mainly because PHP version requirement.

**Comment by dakujem** [comment]
Think about it: maybe writing the two comments above took more time than actually fixing the problem...

But yes, I agree that fixing old releases is pain.

**Comment by dakujem** [comment]
So the problem is only present on PHP 7.2? I have not noticed that, should have stated the PHP version as well, sorry.

**Comment by milo** [comment]
@dg OK 👍

**Comment by milo** [comment]
Tagged https://github.com/nette/tester/releases/tag/v1.7.2
