### ISSUE TITLE
Teamcity native support

### ISSUE THREAD

**Issue by milo** [nette/tester#387]
It is quite long time ago I played with an idea to setup the Teamcity CI localy. But more important things were on the agenda. After reading an article [Integrating Nette Tester and Teamcity CI/CD](https://marcel.sulek.eu/2018/08/26/nette-tester-teamcity-integration.html) by @veproza I refresed the idea and I'm playing with it these days.

Would be someone else pleased by native support in Tester? By this I mean:
- Teamcity OutputHandler
- test run duration (probably by `Test::$testStarted` and `Test::$testFinished`)
- multiple coverage report files
- maybe Teamcity coverage format writer
- maybe other things I'll discover during achiving experiences with Teamcity

Please emoji 👍👎 or comment.

**Comment by f3l1x** [comment]
Good idea 👍, but unfortunately I'm not using TC.

**Comment by veproza** [comment]
My personal take would be to enrich the API with some sort of `testStarted` callback (similar to what I have done [here](https://github.com/veproza/tester/commit/d3f4ad2c500d2b927eb372ec2be9b2f594bec9bc)), or a timing property as you suggested. That would enable anybody improve whatever reporter they are using. It could even enable some improvements of CLI reporter, as you could see which tests are in progress.

Also having more outputs would be useful, possibly just by passing more `-o` arguments (eg. `-o machine.xml -o human.html`).

As for the TeamCity OutputHandler, I'm not sure if Teamcity is so widely used that it is beneficial to bake its OutputHandler directly into Tester. Maybe it would be better to make a list or a repository of "recommended" output handlers. That would hopefully enable some decentralisation so that you wouldn't have to maintain an OutputHandler for each CI/CD solution, but rather "outsource" that to individual maintainers.

**Comment by milo** [comment]
Seems to me better to record start/stop event time as close to reality as possible. Moreover, adding new OutputHandler interface method is a big one BC break.

> Also having more outputs would be useful, possibly just by passing more -o arguments (eg. -o machine.xml -o human.html).

Are you sure about `-o`? As I read your article, multiple `--coverage` would be handy. Anyway, for multiple `-o` is there #329 PR.

And about integrating TC into Tester directly... that's always a question. You mentioned, that Jiří Pudil uses it for PhpStorm plugin (@jiripudil Is that correct, that PhpStorm uses TC format internally too?). I thing that better support for such wide-used tool as PhpStorm is worth it.

**Comment by jiripudil** [comment]
> Is that correct, that PhpStorm uses TC format internally too?

That is indeed correct. Test duration is a nice addition too :+1: I agree with @veproza that reporting the actual start of the test would pave the way for a better UX, but I also agree with @milo that it's an unnecessary BC break too soon after the last major release. I'd postpone that until a 3.0 release is considered, and stick with a property in Test for now.

**Comment by dg** [comment]
I closing for lack of interest.
