### ISSUE TITLE
PHP 7.4 support

### ISSUE THREAD

**Issue by dakujem** [nette/tester#414]
Hey guys, I can see the commit already in the `master`, but it would be awesome to be able to use tester with PHP 7.4 .... well ... for testing for the upcomming 7.4 version, right.

The commit has been sitting there for over a month now and it does not look like a BCB, so why not release it? :-)

Thank you for the consideration.

**Comment by mabar** [comment]
Just use dev-master or v2.4 alias. Stable version of library should not be based on unstable version of language

**Comment by dakujem** [comment]
It would not be _based_ on an unstable version, it would just support it, right?

I'm aware of the option to use a branch instead of a tag, but I prefer using tags. Until then packages using tester `^2.3` (for example) will fail.

**Comment by mabar** [comment]
Thing is - if php 7.4 changes it's behavior in stable version then library may got broken again and there's a release which "fixes" problem but in reality not. It's generally simpler for maintainer to release as stable fixes for only stable versions of language.

> I'm aware of the option to use a branch instead of a tag, but I prefer using tags.
That's why branch aliases exists. Current master is alias to [v2.4-dev](https://github.com/nette/tester/blob/master/composer.json#L25) which allows you to install `^2.4` same way as stable releases. It just needs you to add `"minimum-stability": "dev",` and preferably also `"prefer-stable": true,` to your `composer.json`

**Comment by dakujem** [comment]
@mabar thank you for this valuable information! I did not see the 2.4 tag and it did not occur to me that I could use the alias as a version tag constraint! This hopefully solves my problem.

Furthermore, you are right about stable versions being released for stable PHP versions, I was under the impression the public interface is stable already (was frozen ~2 months ago for PHP 7.4).

Should we close this or will you keep it open until 2.4 stable is released?
